MiBanco/Controllers/ClienteController.cs
using AutoMapper;
using MiBanco.App_Start;
using MiBancoService.Application.Contracts.Services;
using MiBancoService.Application.DTOs.Responses;
using MiBancoService.Domain.Models;
using MiBancoService.Domain.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MiBanco.Controllers
{
    public class ClienteController : Controller
    {

        private readonly IClienteService _clienteService;
        private readonly ITarjetaService _tarjetaService;

        public ClienteController(IClienteService clienteService, ITarjetaService tarjetaService) 
        {
            _clienteService = clienteService;
            _tarjetaService = tarjetaService;
        }


        public ActionResult Index()
        {

            return View();
        }

        public async Task<ActionResult> ConsultaCliente(ClienteVM vm = null)
        {
            var DtoCliente = GetParameterSearch(vm);
            DtoCliente.search = Request.Form.GetValues("search[value]")[0];

            var Result = await _clienteService.ObtenerCliente(DtoCliente);

            return Json(new
            {
                draw = "",
                vm.length,
                recordsFiltered = Result.TotalRecords.ToString(),
                recordsTotal = Result.TotalRecords.ToString(),
                data = from datos in Result.ResultList
                       select new
                       {
                           datos.Codigo
                          ,datos.Nombre
                          ,datos.Apellido
                          ,datos.NumeroContacto
                          ,datos.Ocupacion
                          ,Estado = datos.Estado ? "Activo" : "Inactivo"
                       }

            }, JsonRequestBehavior.AllowGet);
        }

        private static ClienteDTO GetParameterSearch(ClienteVM Vm)
        {
            var vistaAlmacen = new ClienteDTO
            {
                start = Utils.CalculaNumeroPagina(int.Parse(Vm.start), Vm.length).ToString()
               ,length = Vm.length
               ,Nombre = Vm.Nombre
            };
            return vistaAlmacen;
        }


        // GET: Cliente/Create
        [HttpGet]
        public async Task<ActionResult> Create(int Codigo = 0)
        {
            var Vm = new ClienteVM();

            if (Codigo > 0)
            {
                var Result = await _clienteService.ObtenerClienteByCodigo(Codigo);
                var ResultTarjeta = await _tarjetaService.ObtenerTarjetaByCliente(Codigo);
                var ListTarjeta = ConvertVM.ConvertToTarjetaVm(ResultTarjeta.ResultList);
                Vm = ConvertVM.ConvertToClienteVm(Result.ResultObject);
                Vm.TarjetaVMs = ListTarjeta;
            }
            
            return View("CreateCliente",Vm);
        }


        // POST: Cliente/GetPartialListadoTarjeta
        [HttpPost]
        public async Task<ActionResult> GetPartialListadoTarjeta(int CodigoCliente = 0)
        {
            var Vm = new List<TarjetaVM>();

            var Result = await _tarjetaService.ObtenerTarjetaByCliente(CodigoCliente);
            var ListTarjeta = ConvertVM.ConvertToTarjetaVm(Result.ResultList);


            return PartialView("Partials/_Tarjetas", ListTarjeta);
        }


        // POST: Cliente/Create 
        [HttpPost]
        public async Task<ActionResult> Create(ClienteVM Vm)
        {
            var Result = new OperationResult<ClienteDTO>();

            if(Vm.Codigo > 0)
                 Result = await _clienteService.ObtenerClienteByCodigo(Vm.Codigo);

            ValidaCreacionCliente(Result.ResultObject);

            if (ModelState.IsValid)
            {
                var DtoCliente = ConvertVM.ConvertToClienteDto(Vm);
                Result = await _clienteService.GuardarCliente(DtoCliente);
            }
            else {
                Result.Success = false;
                Result.Warning = true;
                Result.Messages = Utils.GetModelStateMessage(ModelState);
            }

            return Json(new
            {
                Result.Success,
                Result.Warning,
                Result.Messages
            }, JsonRequestBehavior.AllowGet);
          
        }

        public void ValidaCreacionCliente(ClienteDTO Dto)
        {
            if (Dto != null)
            {
                if (!Dto.Estado)
                    ModelState.AddModelError(nameof(Dto.Estado), "Estimado usuario el cliente que está intentando actualizar se encuentra INACTIVO, favor recargue la página nuevamente para poder activarlo. ");
            }
        }


        // POST: AcivarUsuario
        [HttpPost]
        public async Task<ActionResult> AcivarUsuario(int CodigoActivacion)
        {
   
            var Result = await _clienteService.ActivarUsuario(CodigoActivacion);

            return Json(new
            {
                Result.Success,
                Result.Warning,
                Result.Messages
            }, JsonRequestBehavior.AllowGet);

        }

    }
}

MiBanco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiBanco/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>
    <!-- Bootstrap core CSS-->

    <link href="~/Template2/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Custom fonts for this template-->
    <link href="~/Template2/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    @RenderSection("Style", required: false)


    <!-- Custom styles for this template-->
    <link href="~/Template2/css/sb-admin.css" rel="stylesheet">

    <link href="~/Template2/css/jquery-ui.css" rel="stylesheet" />

    <style type="text/css">
        .input-validation-error {
            border-color: red
        }



        span.label-danger {
            color: red
        }

        .field-validation-error {
            color: red
        }

        /*span {
            color: red
        }*/

    </style>

</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                        
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mantenimiento Cliente">
                        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#CrearCliente" data-parent="#exampleAccordion">
                            <i class="fa fa-fw fa-wrench"></i>
                            <span class="nav-link-text">Mantenimiento Clientes</span>
                        </a>

                        <ul class="sidenav-second-level collapse" id="CrearCliente">

                                <li>
                                    <a href="@Url.Action("Create", "Cliente")">Crear cliente </a>
                                </li>                           
                          
                        </ul>
                    </li> 
            </ul>



            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-envelope"></i>
                        <span class="d-lg-none">
                            Messages
                            <span class="badge badge-pill badge-primary">12 New</span>
                        </span>
                        <span class="indicator text-primary d-none d-lg-block">
                            <i class="fa fa-fw fa-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">New Messages:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>David Miller</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>Jane Smith</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>John Doe</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="#">View all messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-bell"></i>
                        <span class="d-lg-none">
                            Alerts
                            <span class="badge badge-pill badge-warning">6 New</span>
                        </span>
                        <span class="indicator text-warning d-none d-lg-block">
                            <i class="fa fa-fw fa-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">New Alerts:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-danger">
                                <strong>
                                    <i class="fa fa-long-arrow-down fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="#">View all alerts</a>
                    </div>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Search for...">
                            <span class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out"></i>Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">
            <!-- Breadcrumbs-->
            <div class="row">
                <div class="col-12">

                    @RenderBody()


                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright © Your Website 2018</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>



        <script src="~/Template2/vendor/jquery/jquery.min.js"></script>

        <script src="~/Template2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Core plugin JavaScript-->
        <script src="~/Template2/vendor/jquery-easing/jquery.easing.min.js"></script>


        @RenderSection("Script", required: false)

        <script src="~/Template2/js/jquery.validate.js"></script>
        <script src="~/Template2/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/jquery.unobtrusive-ajax.js"></script>

        <!-- Custom scripts for -->
        <script src="~/Template2/js/sb-admin.min.js"></script>
        <!-- Custom scripts for this page-->
        <script src="~/Template2/js/sb-admin-datatables.min.js"></script>


        <script src="~/Scripts/jquery.blockUI.js"></script>
        <script src="~/Scripts/bootbox.min.js"></script>

        <script src="~/Scripts/jquery-ui.js"></script>
        <script src="~/ScriptSetting/jquery.mask.js"></script>
        <script src="~/ScriptSetting/ScriptSetting.js"></script>

    </div>




</body>
</html>