MiBanco/Controllers/TarjetaController.cs
using MiBancoService.Application.Contracts.Services;
using MiBancoService.Application.DTOs.Responses;
using MiBancoService.Domain.Models;
using MiBancoService.Domain.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MiBanco.Controllers
{
    public class TarjetaController : Controller
    {
        private readonly IClienteService _clienteService;
        private readonly ITarjetaService _tarjetaService;

        public TarjetaController(ITarjetaService tarjetaService, IClienteService clienteService)
        {
            _tarjetaService = tarjetaService;
            _clienteService = clienteService;
        }


        // GET: Tarjeta/Create
        [HttpPost]
        public async Task<ActionResult> GetPartialCreate(int CodigoCliente = 0, int CodigoTarjeta = 0)
        {
            var Vm = new TarjetaVM();
           
            if (CodigoTarjeta > 0)
            {
                  var Result = await _tarjetaService.OtenerTarjetaByCodigo(CodigoTarjeta);
                          Vm = ConvertVM.ConvertToTarjetaVm(Result.ResultObject);
            }

            var TipoResult = await _tarjetaService.ObtenerTiposTarjeta();
            Vm.DDlTipoTarjeta = new SelectList(TipoResult.ResultList, nameof(TipoResult.ResultObject.TipoTarjetaId), nameof(TipoResult.ResultObject.Descripcion));
            Vm.CodigoCliente = CodigoCliente;

            return PartialView("Partials/_CrearTarjeta", Vm);
        }
        
        // POST: Tarjeta/Create
        [HttpPost]
        public async Task<ActionResult> Create(TarjetaVM Vm)
        {
             var DtoTarjeta = ConvertVM.ConvertToTarjetaDto(Vm);
            var Result = new OperationResult<TarjetaDTO>();

               var ResultCliente = await _clienteService.ObtenerClienteByCodigo(Vm.CodigoCliente);
                ValidaCreacionTarjetaPorClietne(ResultCliente.ResultObject);
                ValidaTarjeta(Vm);

            if (ModelState.IsValid)
            {
                Result = await _tarjetaService.GuardarTarjeta(DtoTarjeta);
            }
            else {
                Result.Success = false;
                Result.Warning = true;
                Result.Messages = Utils.GetModelStateMessage(ModelState);
            }

            return Json(new
            {
                Result.Success,
                Result.Warning,
                Result.Messages
            }, JsonRequestBehavior.AllowGet);

        }

        public void ValidaCreacionTarjetaPorClietne(ClienteDTO Dto)
        {            
            if (Dto != null)
            {
                if (!Dto.Estado)
                    ModelState.AddModelError(nameof(Dto.Estado), "Estimado usuario el cliente al que está intentando agregarle la tarjeta se encuentra INACTIVO, favor recargue la página nuevamente para poder activarlo. ");
            }
        }

        public void ValidaTarjeta(TarjetaVM Vm)
        {
            var Tarjeta = _tarjetaService.OtenerTarjetaByNumero(Vm.Numero).ResultObject;

            if (Tarjeta != null && Vm.CodigoTarjeta <= 0)
            {                
                    ModelState.AddModelError(nameof(Vm.Numero), "Estimado usuario el numero de tarjeta que esta intentando utilizar ya esta registrado. ");
            }

            if (Tarjeta != null && Vm.CodigoTarjeta > 0)
            {
                if(Tarjeta.CodigoTarjeta != Vm.CodigoTarjeta)
                    ModelState.AddModelError(nameof(Vm.Numero), "Estimado usuario el numero de tarjeta que esta intentando utilizar ya esta registrado. ");
            }
        }


    }
}

MiBanco/Views/Tarjeta/Partials/_CrearTarjeta.cshtml
@model MiBancoService.Domain.Models.TarjetaVM



<h2>Creacion de Tarjetas</h2>

<div class="MesajeEspera" style="display:none">
    <img src="~/Images/ajax-loader.gif" id="ajaxLoader" />
    <p> Procesando por favor espere.</p>
</div>


<div class="card mb-5">
    <div class="card-header">
        <i class="fa fa-bar-chart"></i> Registre la información del cliente.
    </div>
    <div class="card-body">

        @using (Ajax.BeginForm("Create", "Tarjeta",
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    LoadingElementId = "ajaxLoader",
                    OnSuccess = "onTarjetaSucess",
                    OnFailure = "onTarjetafaile",
                    UpdateTargetId = "alerta"
                },
                new
                {
                    @id = "Ajaxformtarjeta",
                    @class = "form-horizontal",
                    role = "form"
                }))
        {
        <div class="row">

            @Html.HiddenFor(x => x.CodigoTarjeta)
            @Html.HiddenFor(x => x.CodigoCliente)

            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoTarjetaId)
                    @Html.DropDownListFor(x => x.TipoTarjetaId, Model.DDlTipoTarjeta != null ?
                    Model.DDlTipoTarjeta : Enumerable.Empty<SelectListItem>(),
                    " - Seleccione", new { @class = "form-control" }
                   )
                    @Html.ValidationMessageFor(model => model.TipoTarjetaId)
                </div>
            </div>

            <div class="col-lg-3">
                @Html.LabelFor(model => model.Banco)
                @Html.TextBoxFor(model => model.Banco, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Banco, null, new { @class = "label label-danger" })
            </div>

            <div class="col-lg-4">
                @Html.LabelFor(model => model.Numero)
                @Html.TextBoxFor(model => model.Numero, new { @class = "form-control NumeroTarjeta" })
                @Html.ValidationMessageFor(model => model.Numero, null, new { @class = "label label-danger" })
            </div>

        </div>

            <div class="row">

                <div class="col-lg-3">
                    @Html.LabelFor(model => model.MesVence)
                    @Html.TextBoxFor(model => model.MesVence, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MesVence, null, new { @class = "label label-danger" })
                </div>

                <div class="col-lg-3">
                    @Html.LabelFor(model => model.AnioVence)
                    @Html.TextBoxFor(model => model.AnioVence, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AnioVence, null, new { @class = "label label-danger" })
                </div>
                             

            </div>




            <br />



            <div class="row">
                <div class="col-lg-6">
                    <div>
                        <input type="submit" value="Guardar" class="btn btn-outline btn-primary" />
                    </div>
                </div>
            </div>

        }
    </div>
    <div class="card-footer small text-muted"></div>
</div>